In [54]:
import numpy as np
import pandas as pd

In [55]:
df = pd.read_csv('data/customer.csv')
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


In [57]:
df = df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [58]:
X= df.iloc[:,0:2]
X

review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [59]:
y= df.iloc[:,-1]
y

0      No
1      No
2      No
3      No
4      No
5     Yes
6      No
7     Yes
8      No
9     Yes
10    Yes
11    Yes
12     No
13     No
14    Yes
15     No
16    Yes
17    Yes
18     No
19    Yes
20    Yes
21     No
22    Yes
23     No
24    Yes
25     No
26     No
27     No
28     No
29    Yes
30     No
31    Yes
32    Yes
33    Yes
34     No
35    Yes
36    Yes
37    Yes
38     No
39     No
40     No
41    Yes
42    Yes
43     No
44     No
45    Yes
46     No
47    Yes
48    Yes
49     No
Name: purchased, dtype: object

In [60]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [61]:
X_train

review education
24  Average        PG
1      Poor        UG
12     Poor    School
16     Poor        UG
33     Good        PG
35     Poor    School
41     Good        PG
39     Poor        PG
32  Average        UG
11     Good        UG
5   Average    School
0   Average    School
27     Poor        PG
3      Good        PG
7      Poor    School
29  Average        UG
8   Average        UG
13  Average    School
15     Poor        UG
6      Good    School
30  Average        UG
2      Good        PG
34  Average    School
26     Poor        PG
4   Average        UG
14     Poor        PG
36     Good        UG
47     Good        PG
37  Average        PG
25     Good    School
38     Good    School
42     Good        PG
19     Poor        PG
40     Good    School
10     Good        UG
46     Poor        PG
28     Poor    School
43     Poor        PG
31     Poor    School
20  Average    School

In [62]:
from sklearn.preprocessing import OrdinalEncoder

In [63]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [64]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [65]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [66]:
X_train

array([[1., 2.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [1., 0.]])

In [67]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [68]:
X_train

array([[1., 2.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [1., 0.]])

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
le = LabelEncoder()

In [71]:
le.fit(y_train)

LabelEncoder()

In [72]:
le.classes_


array(['No', 'Yes'], dtype=object)

In [73]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [74]:
y_train

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1])